# version: '3.9'
services:
  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile
    image: ashwinrdocker/px_v2:backend  # Single repo with "backend" tag
    ports:
      - "10000:10000" 
    environment:
      - NODE_ENV=production

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend 
      args:
        VITE_REACT_APP_BASE_URL: ${VITE_REACT_APP_BASE_URL}
    image: ashwinrdocker/px_v2:frontend  # Single repo with "frontend" tag

    ports:
      - "3000:3000"  # Maps host port 80 to container port 80 (served by Nginx in this case)
    depends_on:
      - backend  # Ensures backend starts before frontend
    
    environment:
      # - REACT_APP_BASE_URL=http://backend:10000 
      - VITE_REACT_APP_BASE_URL=${VITE_REACT_APP_BASE_URL}

    restart: unless-stopped
