name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Set up Docker-in-Docker service so containers can be run in GitHub Actions
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 3000:3000  # Expose frontend port (if necessary)
          - 5000:5000  # Expose backend port (if necessary)
        volumes:
          - /var/lib/docker

    steps:
      # Step 1: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # Step 3: Build and start services with Docker Compose
      - name: Build and start services
        run: |
            export VITE_REACT_APP_BASE_URL=${{ secrets.VITE_REACT_APP_BASE_URL }}
            docker-compose build --build-arg VITE_REACT_APP_BASE_URL=$VITE_REACT_APP_BASE_URL
            docker-compose up -d

         # Step 5: Push Docker images to Docker Hub
      - name: Push Docker images
        run: |
          docker-compose -f docker-compose.yml push
